In [1]:
import requests
import pandas as pd

def fetch_crypto_market_cap():
    url = 'https://api.coingecko.com/api/v3/coins/markets'
    params = {
        'vs_currency': 'usd',
        'order': 'market_cap_desc',
        'per_page': 10,
        'page': 1,
        'sparkline': 'false'
    }
    response = requests.get(url, params=params)
    data = response.json()
    
    market_caps = []
    for coin in data:
        market_caps.append({
            'Name': coin['name'],
            'Symbol': coin['symbol'],
            'Market Cap': coin['market_cap']
        })
    
    df = pd.DataFrame(market_caps)
    return df

# Fetch and display the market cap of top crypto currencies
crypto_market_cap_df = fetch_crypto_market_cap()
crypto_market_cap_df

                Name Symbol     Market Cap
0            Bitcoin    btc  1250813276555
1           Ethereum    eth   311207327359
2             Tether   usdt   119703462585
3                BNB    bnb    83345425830
4             Solana    sol    72510629604
5               USDC   usdc    35646568466
6                XRP    xrp    35045355249
7  Lido Staked Ether  steth    25345068164
8           Dogecoin   doge    17180074534
9            Toncoin    ton    14776230785

In [6]:
import requests
import pandas as pd
def fetch_crypto_market_cap_and_volume():
    url = 'https://api.coingecko.com/api/v3/coins/markets'
    params = {
        'vs_currency': 'usd',
        'order': 'market_cap_desc',
        'per_page': 10,
        'page': 1,
        'sparkline': 'false'
    }
    response = requests.get(url, params=params)
    data = response.json()
    
    market_caps_and_volumes = []
    for coin in data:
        market_caps_and_volumes.append({
            'Name': coin['name'],
            'Symbol': coin['symbol'],
            'Market Cap': coin['market_cap'],
            '24h Volume': coin['total_volume']
        })
    
    df = pd.DataFrame(market_caps_and_volumes)
    return df

# Fetch and display the market cap and 24-hour volume of top crypto currencies
crypto_market_cap_and_volume_df = fetch_crypto_market_cap_and_volume()
crypto_market_cap_and_volume_df

                Name Symbol     Market Cap   24h Volume
0            Bitcoin    btc  1250764250039  33084024925
1           Ethereum    eth   311160992720  16405800447
2             Tether   usdt   119552912192  53687742870
3                BNB    bnb    83314322593   1063084285
4             Solana    sol    72336105990   3121200804
5               USDC   usdc    35530398097   7064507231
6                XRP    xrp    35199781485   2584483456
7  Lido Staked Ether  steth    25329864270     41145647
8           Dogecoin   doge    17192996638   1087074808
9            Toncoin    ton    14801755266    284194200

In [19]:
import yfinance as yf
investment_amount = 100_000_000  # 100M USD
start_date = "2023-10-01"
end_date = "2023-10-10"

# Fetch S&P 500 data
sp500 = yf.Ticker("^GSPC")
sp500_data = sp500.history(start=start_date, end=end_date)

print(sp500_data)

                                  Open         High          Low        Close
Date
2023-10-02 00:00:00-04:00  4284.520020  4300.580078  4260.209961  4288.390137  \
2023-10-03 00:00:00-04:00  4269.750000  4281.149902  4216.450195  4229.450195
2023-10-04 00:00:00-04:00  4233.830078  4268.500000  4220.479980  4263.750000
2023-10-05 00:00:00-04:00  4259.310059  4267.129883  4225.910156  4258.189941
2023-10-06 00:00:00-04:00  4234.790039  4324.100098  4219.549805  4308.500000
2023-10-09 00:00:00-04:00  4289.020020  4341.729980  4283.790039  4335.660156

                               Volume  Dividends  Stock Splits
Date
2023-10-02 00:00:00-04:00  3938660000        0.0           0.0
2023-10-03 00:00:00-04:00  3953830000        0.0           0.0
2023-10-04 00:00:00-04:00  3777600000        0.0           0.0
2023-10-05 00:00:00-04:00  3581470000        0.0           0.0
2023-10-06 00:00:00-04:00  3902030000        0.0           0.0
2023-10-09 00:00:00-04:00  3174630000        0.0           0.0